Repository NikolayRys/Likely, pull requests merged in 2020-05, with the labels that each got.

#178 Minified files in archive
  package.json
  readme.md
Labels: Bug

#169 Keep likely.initiate() as the only way to run the widgets
  source/index.js
  test/index.js
Labels: 3.0, Enhancement

#179 Update VK icon & color
  source/index.styl
  source/services/vkontakte.js
Labels: 3.0, Waiting feedback
